Add_Friend/urls.py
from django.conf.urls import url
from .views import index
from .views import add_friend
from .views import del_friend



urlpatterns = [
url(r'^$', index, name='index'),
url(r'add-friend', add_friend, name='add-friend'),
url(r'del-friend/$', del_friend, name='del-friend'),

        
]

Project1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import update_status.urls as update_status
import profile_page.urls as profile_page
import Add_Friend.urls as Add_Friend
import dashboard.urls as dashboard
import welcome_page.urls as welcome_page

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^update-status/', include(update_status, namespace='update-status')),
	url(r'^profile-page/', include(profile_page, namespace='profile-page')),
	url(r'^Add-Friend/', include(Add_Friend, namespace='Add-Friend')),
	url(r'^dashboard/', include(dashboard, namespace='dashboard')),
	url(r'^$', include(welcome_page, namespace='welcome-page')),
]

dashboard/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
	url(r'^$', index, name='index'),
]

profile_page/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
       url(r'^$', index, name='index'),
]

update_status/urls.py
from django.conf.urls import url
from .views import index, add_todo, del_status

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add_todo', add_todo, name='add_todo'),
	url(r'del-status/$', del_status, name='del-status'),
]

welcome_page/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

Add_Friend/models.py
from django.db import models

# Create your models here.
class ListFriend(models.Model):
    Name = models.CharField(max_length=15)
    URL = models.URLField()
    Date = models.DateTimeField(auto_now_add=True)
	
  
    

dashboard/models.py
from django.db import models

# Create your models here.

profile_page/models.py
from django.db import models
from django.shortcuts import get_object_or_404

class Expertise(models.Model):
    expertise = models.TextField()

class Profile_Page(models.Model):
    name = models.TextField()
    birthday = models.DateField()
    gender = models.TextField()
    expertise = models.ManyToManyField(Expertise)
    description = models.TextField()
    email = models.TextField

    def __str__(self):
        return self.name

    def getBirthday(self):
        return self.birthday

    def getGender(self):
        return self.gender

    def getExpertise(self):
        return self.expertise

    def getDescription(self):
        return self.description

    def getEmail(self):
        return self.email




   

update_status/models.py
from django.db import models


# Create your models here.

class Todo(models.Model):
	description = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)

welcome_page/models.py
from django.db import models

# Create your models here.

Add_Friend/forms.py
from django import forms

class add_form(forms.Form):
    error_messages = {
        'required': 'Please fill this input',
    }
    Name_attrs = {
        'type': 'text',
        'class': 'add-form-input',
        'placeholder':'Enter name'
		
    }
    URL_attrs = {
        'type': 'URL',
        'cols': 50,
        'rows': 4,
        'class': 'add-form-textarea',
        'placeholder':'Enter herokuapp link'
		
    }

    Name = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=Name_attrs))
    URL = forms.CharField(label='', required=True, widget=forms.TextInput(attrs=URL_attrs))

	

update_status/forms.py
from django import forms


class Todo_Form(forms.Form):
	error_messages = {
		'required': 'This field is required!',
		
		}
		
		
	description_attrs = {
	'type': 'text',
	'cols': 100,
	'rows': 4,
	'class': 'todo-form-textarea',
	'placeholder': "what's on your mind?..."
		
	}
	
	description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))
	
	

Add_Friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import ListFriend
from .forms import add_form

# Create your views here.
#List_Friend = {}
response={}
def index(request):
    response['author'] = "Tarsvini"
    listfriend = ListFriend.objects.all()
    response['listfriend'] =listfriend
    html = 'Add_Friend/add_friend.html'
    response['add_form'] = add_form
    return render(request, html, response)
   
	
def add_friend(request):
    form = add_form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()) :
        response['Name'] = request.POST['Name']
        response['URL'] = request.POST['URL']
        listfriend = ListFriend(Name=response['Name'],URL=response['URL'])
        listfriend.save()
        return HttpResponseRedirect('/Add-Friend/')
    else:
        return HttpResponseRedirect('/Add-Friend/')
    

		
def del_friend(request):
    if(request.method == 'POST'):
        del_id_btn = request.POST['del_id']
        ListFriend.objects.filter(id=del_id_btn).delete()
        return HttpResponseRedirect('/Add-Friend/')
    else:
        return HttpResponseRedirect('/Add-Friend/')

dashboard/views.py
from django.shortcuts import render
from update_status.models import Todo
from Add_Friend.models import ListFriend

# Create your views here.
response = {'author': "syuvira"}

def index(request):
    html = 'dashboard/dashboard.html'
    response['statusCount'] = Todo.objects.all().count()
    response['friendsCount'] = ListFriend.objects.all().count()
    response['latestPost'] = Todo.objects.last()
    return render(request, html, response)

profile_page/views.py
from django.shortcuts import render
from datetime import date

name = 'Syuvira' # TODO Implement this
birthday = date(1996, 10, 13) #TODO Implement this, format (Year, Month, Date)
gender = 'Female'
expertise = ["Arts", "Computer", "Sleep"]
description = 'Cat-lover, wanderlust'
email = 'syuvira@whatever.com'

def index(request):
   response = {'name': name, 'birthday': birthday, 'gender': gender, 'expertise': expertise, 'description': description, 'email': email}
   html = 'profile_page/profile_page.html'
   return render(request, html, response)

update_status/views.py
from django.shortcuts import render
from django.db.utils import OperationalError
from django.http import HttpResponseRedirect
from .models import Todo
from .forms import Todo_Form


# Create your views here.

response = {}

def index(request):
	response['author'] = "syuvira" #TODO Implement yourname
	todo = Todo.objects.all()
	response['todo'] = todo
	html = 'update_status/update_status.html'
	response['todo_form'] = Todo_Form
	return render(request, html, response)

	
	
def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['description'] = request.POST['description']
        todo = Todo(description=response['description'])
        todo.save()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

		
def del_status(request):
    if(request.method == 'POST'):
        del_id_btn = request.POST['del_id']
        Todo.objects.filter(id=del_id_btn).delete()
        return HttpResponseRedirect('/update-status/')
    else:
        return HttpResponseRedirect('/update-status/')

welcome_page/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index_welcomepage.html')

Add_Friend/templates/Add_Friend/Layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Add Friend">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
	<link href='https://fonts.googleapis.com/css?family=Architects Daughter' rel='stylesheet'-->


    <title>
        {% block title %} Friends {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "Add_Friend/partials/header.html" %}
    </header>
    <content>
	         
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
			
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "Add_Friend/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

Add_Friend/templates/Add_Friend/partials/footer.html
<p align="center">&copy; syuvira</p>

Add_Friend/templates/Add_Friend/partials/header.html
<!-- Fixed navbar -->
{% load static %}
<style>
  nav ul li a{
    text-align: center;
  }
</style>
<nav  class="navbar navbar-default navbar-static-top" style="background:pink">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="padding-bottom: 5px; padding-top: 0px;" href="{% url 'update-status:index' %}"><img src="{% static 'image/star.png' %}" width="130px" height="60px"s></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'update-status:index' %}"><b> Status </b></a> </li>
        <li><a href="{% url 'profile-page:index' %}"><b> Profile </b></a> </li>
        <li><a href="{% url 'Add-Friend:index' %}"><b> Friends </b></a> </li>
        <li><a href="{% url 'dashboard:index' %}"><b> Stats </b></a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

dashboard/templates/dashboard/dashboard.html
{% extends "dashboard/layout/base.html" %}

{% block content %}
<div class="flex">
	<div class="flex-item">
		<div class="display-picture">
			<img src="https://www.shareicon.net/data/256x256/2016/02/19/721761_people_512x512.png" style="border-radius: 50%; display: block; margin: 0 auto; margin-right: 20px; float: left;" width="200px" height="200px">
		</div>
		<div class="display-title" style="padding: 30px;">
			<h4 style="text-transform: uppercase; font-family: Open Sans; font-weight: bold">Dashboard &amp; Stats</h4>
			<h1 style="margin-top: 1px; margin-left: 20px; font-family: Open Sans; font-weight: bold">{{ name }}</h1>
			<p style="font-size: 20px; font-family: Open Sans"><strong>{{ friendsCount }}</strong> friends <strong>{{ statusCount }}</strong> posts</p>			
		</div>
	</div>	
</div>
<hr/>

<section name="latest-post" id="latest-post">
	<h3><strong>Latest Post</strong></h3>
	<hr/>
	<h3 style="font-family: Open Sans; font-weight: bold;">"{{ latestPost.description }}"</h3>
	<p style="font-family: Open Sans; color: black;">Posted on {{ latestPost.created_date }}</p>
</section>
{% endblock %}

dashboard/templates/dashboard/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="DASHBOARD">
    <meta name="name" content="{{name}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %} Stats {% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "dashboard/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
            </div>
    </content>
    <footer>
       
        {% include "dashboard/partials/footer.html" %}
        
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

dashboard/templates/dashboard/partials/footer.html
<p align="center">&copy; syuvira</p>

dashboard/templates/dashboard/partials/header.html
<!-- Fixed navbar -->
{% load static %}
<style>
  nav ul li a{
    text-align: center;
  }
</style>
<nav  class="navbar navbar-default navbar-static-top" style="background:pink">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="padding-bottom: 5px; padding-top: 0px;" href="{% url 'update-status:index' %}"><img src="{% static 'image/star.png' %}" width="130px" height="60px"s></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'update-status:index' %}"><b> Status </b></a> </li>
        <li><a href="{% url 'profile-page:index' %}"><b> Profile </b></a> </li>
        <li><a href="{% url 'Add-Friend:index' %}"><b> Friends </b></a> </li>
        <li><a href="{% url 'dashboard:index' %}"><b> Stats </b></a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

profile_page/templates/profile_page/layout/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="description" content="PROFILE PAGE">
    <meta name="name" content="{{name}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    

    <title> 
        {% block title %} Profile Of {{name}}{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "profile_page/partials/header.html" %}
    </header>
    <content>
        <div class="container">
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
            </div>
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "profile_page/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>

profile_page/templates/profile_page/partials/footer.html
<p align="center">&copy; syuvira</p>

profile_page/templates/profile_page/partials/header.html
<!-- Fixed navbar -->
{% load static %}
<style>
  nav ul li a{
    text-align: center;
  }
</style>
<nav  class="navbar navbar-default navbar-static-top" style="background:pink">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="padding-bottom: 5px; padding-top: 0px;" href="{% url 'update-status:index' %}"><img src="{% static 'image/star.png' %}" width="130px" height="60px"s></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'update-status:index' %}"><b> Status </b></a> </li>
        <li><a href="{% url 'profile-page:index' %}"><b> Profile </b></a> </li>
        <li><a href="{% url 'Add-Friend:index' %}"><b> Friends </b></a> </li>
        <li><a href="{% url 'dashboard:index' %}"><b> Stats </b></a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

profile_page/templates/profile_page/profile_page.html
{% extends "profile_page/layout/base.html" %}

{% block content %}
<style>
* {
    box-sizing: border-box;
}

body {
    margin: 0;
}

.column {
    float: left;
    padding: 10px;
}

.left {
  width: 30%;
}

.middle {
width: 15%;
}

.right {
  width: 55%;
}

.row:after {
    content: "";
    display: table;
    clear: both;
}

.button {
    border-radius: 8px;
    text-align: center;
}
</style>
<h1>Profile</h1>
<div>
    <p style="text-align:center; margin-top:0px; margin-bottom:0px; padding:0px;">
    <img align="center" src="https://www.shareicon.net/data/256x256/2016/02/19/721761_people_512x512.png" alt="people icon" height="120" width="120">
    <h2 align="center">{{ name }}</h2>
    </p>
</div>
<section name="profile">
<div class="row">
  <div class="column left">
  </div>
  <div class="column middle">
    <article><b>Birthday</b></article><br>
    <article><b>Gender</b></article><br>
    <article><b>Expertise</b></article><br>
    <article><b>Description</b></article><br>
    <article><b>Email</b></article>
  </div>
  <div class="column right">
    <article>{{ birthday }}</article><br>
    <article>{{ gender }}</article><br>
    <script>
    	var exp = {{ expertise|safe }};
        var i=0;
        while (exp.length) {
  			var tempExp = exp.pop();
  			document.write('<button class="button" style="background:pink;">' + tempExp + "</button>" + " ");
		}
    </script><br><br>
    <article>{{ description }}</article><br>
    <article>{{ email }}</article><br>
  </div>
</div>
</section>
{% endblock %}

update_status/templates/update_status/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="UPDATE STATUS">
    <meta name="author" content="{{author}}">
	
    <!-- bootstrap csss -->
	
	<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}" />

    <title>
        {% block title %} Update Status{% endblock %}
    </title>
</head>

<body>
    <header>
        {% include "update_status/partials/header.html" %}
    </header>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "update_status/partials/footer.html" %}
        {% endblock %}
    </footer>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
		$(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });

    </script>
</body>
</html>

update_status/templates/update_status/partials/footer.html
<p align="center">&copy; syuvira</p>

update_status/templates/update_status/partials/header.html
<!-- Fixed navbar -->
{% load static %}
<style>
  nav ul li a{
    text-align: center;
  }
</style>
<nav  class="navbar navbar-default navbar-static-top" style="background:pink">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" style="padding-bottom: 5px; padding-top: 0px;" href="{% url 'update-status:index' %}"><img src="{% static 'image/star.png' %}" width="130px" height="60px"s></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'update-status:index' %}"><b> Status </b></a> </li>
        <li><a href="{% url 'profile-page:index' %}"><b> Profile </b></a> </li>
        <li><a href="{% url 'Add-Friend:index' %}"><b> Friends </b></a> </li>
        <li><a href="{% url 'dashboard:index' %}"><b> Stats </b></a> </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>